# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: 
  theme_night: aga
  font: edo
  font_size: M
  
# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: 'ProfessionalService'
    org_name: ''
    description: 'Quantum Club IIT Jodhpur.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false
    
# Site footer

footer:
  copyright:
    notice: '© {year} Quantum Club IIT Jodhpur. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  show_translations: true


# Localization

locale:
  date_format: 'Jan 10, 2024'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/ShisheerKaushik24/QCIG_iitj'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'giscus'
    disqus:
      shortname: 'QC-IITJ'
      show_count: true
    commento:
      url: ''
    giscus:
      repo: 'ShisheerKaushik24/QCIG_iitj'
      repo_id: 'R_kgDOLBbIug'
      category: 'Show and tell'
      category_id: 'DIC_kwDOLBbIus4CcO0V'
      mapping: "pathname"  # How Utterances will match comment to page
      label: "comment"     # Label applied to issue by utteranc.es bot
      theme: "preferred_color_scheme"        # What theme to use
      reactions_enabled: "1"
      input-position: "top" # Where to put the new comment box (ini nambahin send
  search:
    provider:
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Citation style

publications:
  date_format: January 2024
  citation_style: apa
