# Theme metadata
name = "aga"

[dark]
  # Primary
  primary = "#f6bd4b"

  # Menu
  menu_primary = "#211433" #"#533483"
  menu_text = "#fef9ff"
  menu_text_active = "#f6bd4b"
  menu_title = "#fef9ff"

  # Backgrounds
  #background = "#000"
  home_section_odd = "#1A1A2E"
  home_section_even = "#16213E"

  # Links
  link = "#f6bd4b"
  link_hover = "#f6bd4b"
